server:
  port: 8080
  path: /api/comander

spring:
  application:
    name: comander
  datasource:
    url: jdbc:postgresql://localhost:5432/infra_db
    username: infra
    schema: comander
    password: please_change_me
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        default_schema: comander
        format_sql: true

  flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
      schemas: comander
      table: flyway_schema_history
      placeholder-replacement: true
      placeholders:
        schema: comander



